/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesReformulacaoSiteFundacaoGrupoBoticarioRouteImport } from './routes/cases.reformulacao-site-fundacao-grupo-boticario'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesReformulacaoSiteFundacaoGrupoBoticarioRoute =
  CasesReformulacaoSiteFundacaoGrupoBoticarioRouteImport.update({
    id: '/cases/reformulacao-site-fundacao-grupo-boticario',
    path: '/cases/reformulacao-site-fundacao-grupo-boticario',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/cases/reformulacao-site-fundacao-grupo-boticario': typeof CasesReformulacaoSiteFundacaoGrupoBoticarioRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/cases/reformulacao-site-fundacao-grupo-boticario': typeof CasesReformulacaoSiteFundacaoGrupoBoticarioRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/cases/reformulacao-site-fundacao-grupo-boticario': typeof CasesReformulacaoSiteFundacaoGrupoBoticarioRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sobre'
    | '/cases/reformulacao-site-fundacao-grupo-boticario'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sobre'
    | '/cases/reformulacao-site-fundacao-grupo-boticario'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/sobre'
    | '/cases/reformulacao-site-fundacao-grupo-boticario'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SobreRoute: typeof SobreRoute
  CasesReformulacaoSiteFundacaoGrupoBoticarioRoute: typeof CasesReformulacaoSiteFundacaoGrupoBoticarioRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/reformulacao-site-fundacao-grupo-boticario': {
      id: '/cases/reformulacao-site-fundacao-grupo-boticario'
      path: '/cases/reformulacao-site-fundacao-grupo-boticario'
      fullPath: '/cases/reformulacao-site-fundacao-grupo-boticario'
      preLoaderRoute: typeof CasesReformulacaoSiteFundacaoGrupoBoticarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SobreRoute: SobreRoute,
  CasesReformulacaoSiteFundacaoGrupoBoticarioRoute:
    CasesReformulacaoSiteFundacaoGrupoBoticarioRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
